//! Help metadata for the NumPy-compatible sandbox module.

use crate::sandbox::{FnDoc, ModuleDoc, Param, ParamType, ReturnType};

pub(crate) static NUMPY_DOC: ModuleDoc = ModuleDoc {
    name: "numx",
    summary: "Multi-dimensional array and linear algebra operations",
    functions: &[
        FnDoc {
            name: "array",
            description: "Create array from data. 1D: [1,2,3]. 2D: [[1,2],[3,4]].",
            params: &[Param {
                name: "data",
                short: None,
                typ: ParamType::Table,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: Some(r#"local a = numx.array({{1,2,3},{4,5,6}}) -- 2x3 matrix"#),
        },
        FnDoc {
            name: "zeros",
            description: "Array of zeros. Shape: n or {rows, cols}.",
            params: &[Param {
                name: "shape",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: Some(r#"numx.zeros({3, 4}) -- 3x4 matrix of zeros"#),
        },
        FnDoc {
            name: "ones",
            description: "Array of ones.",
            params: &[Param {
                name: "shape",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: Some(r#"numx.ones(5) -- 1D array of five ones"#),
        },
        FnDoc {
            name: "full",
            description: "Array filled with val.",
            params: &[
                Param {
                    name: "shape",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "val",
                    short: None,
                    typ: ParamType::Number,
                    required: true,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "arange",
            description: "Evenly spaced values in [start, stop).",
            params: &[
                Param {
                    name: "start",
                    short: None,
                    typ: ParamType::Number,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "stop",
                    short: None,
                    typ: ParamType::Number,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "step",
                    short: None,
                    typ: ParamType::Number,
                    required: false,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: Some(r#"numx.arange(0, 10, 2) -- {0,2,4,6,8}"#),
        },
        FnDoc {
            name: "linspace",
            description: "count evenly spaced values in [start, stop].",
            params: &[
                Param {
                    name: "start",
                    short: None,
                    typ: ParamType::Number,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "stop",
                    short: None,
                    typ: ParamType::Number,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "count",
                    short: None,
                    typ: ParamType::Number,
                    required: true,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: Some(r#"numx.linspace(0, 1, 5) -- {0, 0.25, 0.5, 0.75, 1}"#),
        },
        FnDoc {
            name: "eye",
            description: "n×n identity matrix.",
            params: &[Param {
                name: "n",
                short: None,
                typ: ParamType::Number,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "diag",
            description: "Diagonal matrix from 1D array or list.",
            params: &[Param {
                name: "values",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "add",
            description: "Element-wise addition. Supports scalar broadcasting.",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "b",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "sub",
            description: "Element-wise subtraction.",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "b",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "mul",
            description: "Element-wise multiplication.",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "b",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "div",
            description: "Element-wise division.",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "b",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "pow",
            description: "Element-wise power.",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "exp",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "abs",
            description: "Element-wise absolute value.",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "sqrt",
            description: "Element-wise square root.",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "log",
            description: "Element-wise natural logarithm.",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "exp",
            description: "Element-wise exponential.",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "sin",
            description: "Element-wise sine.",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "cos",
            description: "Element-wise cosine.",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "tan",
            description: "Element-wise tangent.",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "floor",
            description: "Element-wise floor.",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "ceil",
            description: "Element-wise ceiling.",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "round",
            description: "Element-wise rounding.",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "decimals",
                    short: None,
                    typ: ParamType::Number,
                    required: false,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "sum",
            description: "Sum. axis=nil: total, 0: along rows, 1: along cols.",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "axis",
                    short: None,
                    typ: ParamType::Number,
                    required: false,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: Some(r#"numx.sum({1, 2, 3, 4}) -- 10"#),
        },
        FnDoc {
            name: "mean",
            description: "Mean.",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "axis",
                    short: None,
                    typ: ParamType::Number,
                    required: false,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: Some(r#"numx.mean({10, 20, 30}) -- 20"#),
        },
        FnDoc {
            name: "std",
            description: "Standard deviation (population).",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "axis",
                    short: None,
                    typ: ParamType::Number,
                    required: false,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "var",
            description: "Variance (population).",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "axis",
                    short: None,
                    typ: ParamType::Number,
                    required: false,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "min",
            description: "Minimum.",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "axis",
                    short: None,
                    typ: ParamType::Number,
                    required: false,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "max",
            description: "Maximum.",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "axis",
                    short: None,
                    typ: ParamType::Number,
                    required: false,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "argmin",
            description: "Index of minimum value (1-based).",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Number,
            example: None,
        },
        FnDoc {
            name: "argmax",
            description: "Index of maximum value (1-based).",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Number,
            example: None,
        },
        FnDoc {
            name: "cumsum",
            description: "Cumulative sum.",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "axis",
                    short: None,
                    typ: ParamType::Number,
                    required: false,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "shape",
            description: "Return the shape of an array.",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Table,
            example: None,
        },
        FnDoc {
            name: "reshape",
            description: "Reshape array.",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "shape",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "transpose",
            description: "Transpose a 2D array.",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "flatten",
            description: "Flatten to 1D.",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "concatenate",
            description: "Concatenate arrays along axis.",
            params: &[
                Param {
                    name: "arrays",
                    short: None,
                    typ: ParamType::Table,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "axis",
                    short: None,
                    typ: ParamType::Number,
                    required: false,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "stack",
            description: "Stack arrays along new axis.",
            params: &[
                Param {
                    name: "arrays",
                    short: None,
                    typ: ParamType::Table,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "axis",
                    short: None,
                    typ: ParamType::Number,
                    required: false,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "sort",
            description: "Sort array.",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "axis",
                    short: None,
                    typ: ParamType::Number,
                    required: false,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "argsort",
            description: "Indices that would sort the array (1-based).",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "where_",
            description: "Element-wise conditional: where cond!=0 pick x, else y.",
            params: &[
                Param {
                    name: "cond",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "x",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "y",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: Some(r#"numx.where_({1,0,1}, {10,20,30}, {-1,-2,-3}) -- {10,-2,30}"#),
        },
        FnDoc {
            name: "unique",
            description: "Unique values, sorted.",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "dot",
            description: "Dot product (1D·1D→scalar, 2D·2D→matmul).",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "b",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: Some(r#"numx.dot({1,2,3}, {4,5,6}) -- 32"#),
        },
        FnDoc {
            name: "matmul",
            description: "Matrix multiplication.",
            params: &[
                Param {
                    name: "a",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
                Param {
                    name: "b",
                    short: None,
                    typ: ParamType::Value,
                    required: true,
                    fields: None,
                },
            ],
            returns: ReturnType::Value,
            example: None,
        },
        FnDoc {
            name: "tolist",
            description: "Convert array to a native collection.",
            params: &[Param {
                name: "a",
                short: None,
                typ: ParamType::Value,
                required: true,
                fields: None,
            }],
            returns: ReturnType::Table,
            example: None,
        },
    ],
};

// ── Registration ────────────────────────────────────────────────────
