# Additional string methods: title, capitalize, isdigit, isalpha, isupper, islower, zfill
print("hello world".title())
print("HELLO WORLD".title())
print("hello-world".title())
print("hello".capitalize())
print("HELLO".capitalize())
print("".capitalize())
print("123".isdigit())
print("abc".isdigit())
print("12a".isdigit())
print("".isdigit())
print("abc".isalpha())
print("abc123".isalpha())
print("".isalpha())
print("HELLO".isupper())
print("Hello".isupper())
print("HELLO 123".isupper())
print("".isupper())
print("hello".islower())
print("Hello".islower())
print("hello 123".islower())
print("".islower())
print("42".zfill(5))
print("-42".zfill(5))
print("+42".zfill(5))
print("hello".zfill(3))
